server:
  port: 11111

spring:
  cons-id: ${CONS_ID}
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    url: ${JDBC_URL}
    username: ${PG_LOGIN}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver
logging:
  file:
    name: ok_logs.log

scheduler:
  enabled: true

