server:
  port: 22222

spring:
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
  datasource:
    url: ${JDBC_URL}
    username: ${PG_LOGIN}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver
logging:
  file:
    name: vk_logs.log

scheduler:
  enabled: true

