camunda:
  bpm:
    admin-user:
      id: bakalover
      password: bakalover
server:
  port: 35080

spring:
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    generate-ddl: true
    ddl-auto: create-drop
  jta:
    atomikos:
      datasource:
        unique-resource-name: postgres
        xa-data-source-class-name: org.postgresql.xa.PGXADataSource
        xa-properties:
          url: ${JDBC_URL}
          user: ${PG_LOGIN}
          password: ${PG_PASS}
        max-pool-size: 5

logging:
  file:
    name: blps_logs.log

scheduler:
  enabled: true

